// <auto-generated />
using System;
using Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Data.Migrations
{
    [DbContext(typeof(SistemaAcaiContext))]
    [Migration("20200327092755_first migration")]
    partial class firstmigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Domain.Entities.AcaiSize.AcaiSizeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnName("CREATE_AT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("NOME")
                        .HasMaxLength(50);

                    b.Property<Guid>("OrderId")
                        .HasColumnName("ID_PEDIDO");

                    b.Property<int>("PrepTime")
                        .HasColumnName("TEMPO_PREPARO");

                    b.Property<decimal>("Price")
                        .HasColumnName("PRECO");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnName("UPDATE_AT");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("PEDIDO_TAMANHO");
                });

            modelBuilder.Entity("Domain.Entities.Additional.AdditionalEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnName("CREATE_AT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("NOME")
                        .HasMaxLength(50);

                    b.Property<Guid>("OrderId")
                        .HasColumnName("ID_PEDIDO");

                    b.Property<int>("PrepTime")
                        .HasColumnName("TEMPO_PREPARO");

                    b.Property<decimal>("Price")
                        .HasColumnName("PRECO");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnName("UPDATE_AT");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("PEDIDO_ADICIONAIS");
                });

            modelBuilder.Entity("Domain.Entities.Flavor.FlavorEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnName("CREATE_AT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("NOME")
                        .HasMaxLength(50);

                    b.Property<Guid>("OrderId")
                        .HasColumnName("ID_PEDIDO");

                    b.Property<int>("PrepTime")
                        .HasColumnName("TEMPO_PREPARO");

                    b.Property<decimal>("Price")
                        .HasColumnName("PRECO");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnName("UPDATE_AT");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("PEDIDO_SABOR");
                });

            modelBuilder.Entity("Domain.Entities.Order.OrderEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnName("CREATE_AT");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnName("UPDATE_AT");

                    b.HasKey("Id");

                    b.ToTable("PEDIDO");
                });

            modelBuilder.Entity("Domain.Entities.AcaiSize.AcaiSizeEntity", b =>
                {
                    b.HasOne("Domain.Entities.Order.OrderEntity", "Order")
                        .WithOne("AcaiSize")
                        .HasForeignKey("Domain.Entities.AcaiSize.AcaiSizeEntity", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Domain.Entities.Additional.AdditionalEntity", b =>
                {
                    b.HasOne("Domain.Entities.Order.OrderEntity", "Order")
                        .WithMany("Additional")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Domain.Entities.Flavor.FlavorEntity", b =>
                {
                    b.HasOne("Domain.Entities.Order.OrderEntity", "Order")
                        .WithOne("Flavor")
                        .HasForeignKey("Domain.Entities.Flavor.FlavorEntity", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
